{% set name = "ephem" %}
{% set version = "4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3c4fd64f453e8f40cf862420a70da95a71b6487ace75e8e0cf85d73707db6065

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python


# ephem/tests/test_jpl.py:33: in runTest
#     f = open(self.path)
#              ^^^^^^^^^
# E   AttributeError: 'JPLTest' object has no attribute 'path'
{% set ignore_tests = "test_jpl.py" %}

test:
  imports:
    - ephem
    - ephem._libastro
    - ephem.cities
    - ephem.stars
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -v --tb=short --pyargs ephem -k "not {{ ignore_tests }}"

about:
  home: https://rhodesmill.org/pyephem
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Compute positions of the planets and stars
  description: |
    PyEphem provides an ``ephem`` Python package for performing high-precision
    astronomy computations. The underlying numeric routines are coded in C and
    are the same ones that drive the popular `XEphem`_ astronomy application,
    whose author, Elwood Charles Downey, generously gave permission for their
    use in PyEphem. The name *ephem* is short for the word *ephemeris*, which
    is the traditional term for a table giving the position of a planet,
    asteroid, or comet for a series of dates. The design of PyEphem emphasizes
    convenience and ease of use. Both celestial bodies and the observer's
    location on Earth are represented by Python objects, while dates and
    angles automatically print themselves in standard astronomical formats.
  doc_url: https://rhodesmill.org/pyephem
  dev_url: https://github.com/brandon-rhodes/pyephem

extra:
  recipe-maintainers:
    - bsipocz
    - mwcraig
    - tacaswell
    - ocefpaf
