travis:
  secure:
    BINSTAR_TOKEN: m5oWE1LoBNMNyh2YUNTOupJy1XCGQiB3UsAAwgdXWqefHbVp6s7/Gh2vz7AS+P0LdeK3ArTO4cwJiif/3qzbkw+jjMwiZBHzoRsOVrANb39onVf/ajT7DLeVIhGU4xdYWjd4gwRfRsJLObLlUnpR1pMrzavWQMXAWgxorzdlC3o3yUtvgRRUQEhhDs2sWHwMy4j2lHIiv7Jz9USMx/JyoAm2ZzCynIsDFhqW/JHIdujqr1yIPUh7/ntZFk8Y/bNcmPZKlj0eXn//ZmbEBQsGaTswjbMOKsJ5C4Abktow0MtMn9F2Z3a6eB3H1N2MmnynSnISR9Ihmu7G51iSaZaMzZNgSd4CqjHPnxm3LbW5k0+ZvSuDrYYkel+sdpNDWUz8Sogui1Xcv/fOBYVyLJQVys+yCFiHWmHaOe/d2Wwanu7mOvkBOtBhhLbk/ggfloxQuxuPhO7TjJ2fR1qym1+QT529gNJ0CmD+OgsInWthTP4X442erouBna0x4e8eteiQVcLQKRgeQ/XBCZdamBFBC59h848rb3qZ+td9BaZdU+TrFxDxrEx0J42/uV2TrTMinxwS5WveU2JBN+3iYF8Bfs6fvnflzcpc9k+MVsrakRQaME3ZX7wmuNRempQBd4SRGsU5UjXZDJX5viHswuxnWEEMG3vkBhD0VgfpbqnvSYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
