travis:
  secure:
    BINSTAR_TOKEN: S5LMs7ZZ4KpE6xxD1D0AonsnRGyn14KzvOWoF1arRQDdMHlO8bONqAANgAzed0w5lrzeVhUnmVRk/jyK6h6J9+jUm1nBhg/jvy9BEsXK27/wZ7wbQn7J+mmOghZd5kVivopaiDtgoiGvFeT+g8017+I5pA2gT/73zuLxPfR3ugGPg/3C7hoReRsgdMtafVr0KbQr2GapSnpjuzNpJwZNgOc69GfHJNYpOa8ywnPVbsuvf9xcrVws9PYR0pL43ay+x16gjPTWcKUVsqPeoqNrWK3rBzOo3RM0I4RRjz84cooMg28oHg/ppwYoLrTxb/8oCudCHqLzkKQ+d+csa/G0eu+HtVDrDMasIKtwD7C2208ugugRlgYUxczCQSZoVEv4AEHYw7XycWxe6Gm5RQSRIAqIUXO2VJalDfDCSPYH8fVq7T8oea1SBZB00F6MsR5WrkrReCq2X82lpy8einDIUa3FbsXItaUECdgqXbuor5NbraUSo+ew1tti+A0NhPwUs3P0WxG89ouaoPSLA2/Fy3LpEaDS5RfabS3L7jzZsGr3b+69XwNwnScV160tJzl/Hq1QYUba03K7iWTQOIrcBri03/n1nHf8z5DXHWDIzHhdweaRHRl/kJ+bjEXQQ9MvPdvcTWocUqxm1SQUuE4tGLc8h2ULzKTdH8Bvx3Axx84=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
