appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gbwNdbERpHxv4UYjIOoLWsauwIuCtUWii5XlLKyLzQVFdLjNs2adDeLLnkPqG2QQCO9gIQjMm7Y/M52pLiMfAEW/VFTU0vDMOsFsAyTm4FLdlTtJM8Nk3fK+gNGbuxFxN6BhdxD/DPyFecgnpqdUXDeUZlsthr8Ww+wcFvbZRTjI7fqYqKIHfgHqtQL7iOtg7Ya8pSkYSxmgHm6OFNGll/vjfUCHUoxlkuBwo7mdga9LEme9TyFRmC4QUwlBFUeQzaDNQ2dxnxxik6wJ8xjGTsrrfshGf8TzVjHZSNjUjJiiZYa8TbY6vqCLJHuiggMX4c+u1lYY+7zujIDNYuLappKIqULincrTrKK70I2Lf8ts1xuYbm8Wh6cvYU2CuI6kQNxgFbCL0qlhtvPGqy0TkBsPZAxR3KCO2EWLHlH4FR/BlvLWrr+yLHGU4caQWmw6VpZySsldJ91tKedhuj+sUF2Z1cOPr2YIMzTY6i+k5JlL/MO18cMz900Y3zxoDE9RSTUoiKOq/s+Ohf+SARwWTdxNN+g7wjhjQGuLIdzKr/5HlNIRA8YNUSTM9jsi0yyirZQFMCgupbOnuNc9bqeYRbr4OUGAOJ/oBUM5CdTI4BfI+n3GAxjrgJpWICMfgKQe5R7B4vkpxeiCgO61kjf+s1am5UWss805L8CoysinSl0=}
provider:
  win: azure
